package com.qa.util;

import org.apache.commons.lang3.RandomStringUtils;

public class BaseClass {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		System.out.println(randomString());
		System.out.println(randomStringInt());
		System.out.println(randomSplChar());
		System.out.println(randomInt());
	}
	
	//Returns autogenerated  random String
	public static String randomString() {
		String randomStr = RandomStringUtils.randomAlphabetic(5);
		return randomStr;
	}
	public static String randomStringInt() {
		String randomStr = RandomStringUtils.randomAlphanumeric(6);
		return randomStr;
	}
	
	public static String randomSplChar() {
		String randomStr = RandomStringUtils.random(6);
		return randomStr;
	}
	public static String randomInt() {
		String randomStr = RandomStringUtils.random(4,1, 100, false, true);
		return randomStr;
	}
}
